### ISSUE TITLE
Bug: GwSeries.from_dinogws does not work for series with multiple periods

### ISSUE THREAD

**Issue by buijssimon** [acequia-package/acequia#1]
Hi thanks for providing the package. Much appreciated. The package works perfectly for dinoloket GW-series.  The only thing is when I try to read a location with multiple measuring periods acequia doesn't work as expected. 
[B30G0583001_1.xlsx](https://github.com/acequia-package/acequia/files/4204722/B30G0583001_1.xlsx)

**Comment by tdmeij** [comment]
Hi Simon
Thank you for reporting this bug in GwSeries.from_dinogws(). 
I am sorry for my late reply; not used to getting feedback on acequia yet. I fixed the bug and tested repair with the enclosed jupyter notebook.  
greeting, Thomas de Meij

[bugfix_#1_fromdinogws.zip](https://github.com/acequia-package/acequia/files/4365298/bugfix_.1_fromdinogws.zip)
